apiVersion: v1
kind: Service
metadata:
  name: writefreely
  labels:
    app: writefreely
spec:
  type: ClusterIP
  selector:
    app: writefreely
  ports:
    - name: http
      port: 80
      targetPort: 8080
